name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup SSH Access
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy to server instance
              run: |
                ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
                    set -e  # Exit on any failure

                    # Ensure Docker is installed
                    if ! command -v docker &> /dev/null; then
                        sudo apt-get update
                        sudo apt-get install -y docker.io
                        sudo systemctl enable docker
                        sudo systemctl start docker
                    fi
                    
                    # Ensure Docker Compose is installed
                    if ! command -v docker-compose &> /dev/null; then
                        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                        sudo chmod +x /usr/local/bin/docker-compose
                        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
                    fi

                    # Ensure the user can run Docker
                    sudo usermod -aG docker $USER

                    # Ensure repo exists
                    if [ ! -d "fastapi-book-project" ]; then
                        git clone https://github.com/victor-ok/fastapi-book-project.git
                    fi
                    
                    cd fastapi-book-project
                    git pull origin main

                    # Restart services
                    sudo systemctl restart docker
                    sudo docker-compose down
                    sudo docker-compose up -d --build
                    sudo systemctl restart nginx
                EOF

            - name: Clean Up SSH Key
              if: always()
              run: rm -f ~/.ssh/id_rsa
