name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup SSH Access
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H ${{secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
            
            - name: Deploy to server instance
              run: |
                curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                chmod +x /usr/local/bin/docker-compose
                ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{secrets.SERVER_USER}}@${{ secrets.SERVER_HOST}} << EOF
                    export PATH=/bin:/usr/bin:$PATH  # Ensure all commands work
            
                    # Ensure repo exists
                    if [ ! -d "fastapi-book-project" ]; then
                      git clone https://github.com/victor-ok/fastapi-book-project.git
                    fi
                    
                    cd fastapi-book-project
                    git pull origin main
                    
                    # Restart services
                    docker-compose down
                    docker-compose up -d --build
                    sudo systemctl restart nginx
                  EOF

            - name: Clean Up SSH Key
              if: always()
              run: rm -f ~/.ssh/id_rsa
